### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by r7919**
Assignment 2
linked list implementation of the stack, excluding file handling part
input - arithmetic string
outputs - RPN string, Evaluated RPN

### CODE REVIEW

**Review by grapheo12 — CHANGES_REQUESTED** [review]
Push the second part solution to your repository. Keep this PR as is. Do not start a new. I will merge the two parts together.

**Comment by r7919** [comment]
I have combined both and removed file handling

**Comment by r7919** [comment]
once check the main function you'll realise 👍

**Comment by grapheo12** [comment]
Oh sorry. I realized later. BTW great work.

**Pull request merged**
