### PR TITLE
Update assignment1_1.c

### PR DESCRIPTION
**Pull request by r7919**
removed temp pointer in reverse function

### CODE REVIEW

**Comment by grapheo12** [comment]
You tested it right?
Can you please test my code?

**Comment by r7919** [comment]
yes I have tested mine after the changes it is working fine

**Comment by grapheo12** [comment]
Move your code to the assignments 1 folder and commit.

**Comment by r7919** [comment]
How to move it into the folder?

**Comment by r7919** [comment]
or I'll remove outer one and add another in the folder

**Comment by grapheo12** [comment]
Open File manager. Cut your file and paste it inside the Assignments 1 folder. Then open terminal in the original folder.
Do
 ```
git add .
git commit
git push
```

**Comment by r7919** [comment]
Remove manually the outer one

**Comment by r7919** [comment]
I'll add a new one inside

**Comment by grapheo12** [comment]
Oh I see you don't have the folder. Do this. Copy the clone link of this repo.
Then do
```
git remote add upstream <copied link>
git pull upstream master
```
Folder would appear.

**Comment by r7919** [comment]
Github desktop version is not working on my pc 
some error is occurring 
port 443 not found 
so you remove outer one manually

**Comment by grapheo12** [comment]
Okay I'll do it. Closing this PR.
Please test my code. See of there is any segfault. If there is, raise an issue.

**Pull request closed without merging**
