### PR TITLE
Create assignment1_1_new.c

### PR DESCRIPTION
**Pull request by r7919**

### CODE REVIEW

**Comment by grapheo12** [comment]
Indent main() properly.

**Comment by grapheo12** [comment]
Delete assignment1_1.c

**Comment by r7919** [comment]
your code is working fine 
I have tested it

**Comment by r7919** [comment]
is there any auto-indent  tool in git

**Comment by grapheo12** [comment]
Nah it actually must be there in a text editor. Not in git. Also ypu can delete the file in this patch 4 branch only. No need to open a new PR.

**Comment by grapheo12** [comment]
Just delete manually from the folder. Then commit and push. That's all.

**Pull request closed without merging**
